spring:
  application:
    name: gulimall-secondkill
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.48.110
  rabbitmq:
    host: 192.168.48.110
    port: 5672
    virtual-host: /
  thymeleaf:
    cache: false

server:
  port: 25000

