spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.48.110:3306/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # 凡是返回日期的都会进行格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 关闭thymeleaf缓存
  thymeleaf:
    cache: false
  # redis配置
  redis:
    host: 192.168.48.110
    port: 6379
  # 配置缓存的类型
  cache:
    type: redis
    # 缓存过期时间
    redis:
      time-to-live: 3600000
      # 缓存null值，防止缓存穿透
      cache-null-values: true
      # 如果指定了缓存前缀，则用该值，否则就用缓存名字
      # key-prefix: CACHE_
      use-key-prefix: true
  # session保存类型
  session:
    store-type: redis

mybatis-plus:
  # classpath*表示不止扫描自己类路径下的mapper文件，也会扫描所引用的依赖中的jar包中的类路径也
  mapper-locations: classpath:mapper/**/*.xml
  # 设置所有主键自增
  global-config:
    db-config:
      id-type: auto
      # 配置逻辑删除标志
      logic-delete-value: 1
      logic-not-delete-value: 0
# 配置端口号
server:
  port: 10001
  servlet:
    # session有效期
    session:
      timeout: 30m
logging:
  level:
    com.syong.gulimall: debug



