spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8333
  # 关闭缓存
  thymeleaf:
    cache: false
  redis:
    host: 192.168.48.110
  session:
    store-type: redis
server:
  port: 40000


management:
  endpoints:
    web:
      exposure:
        include: *

