# 配置网关路由规则
spring:
  cloud:
    gateway:
      routes:
#        - id: baidu_route
#          uri: http://www.baidu.com
#          predicates:
#            - Query=url,baidu
#
#        - id: qq_route
#          uri: http://www.qq.com
#          predicates:
#            - Query=url,qq

         # 商品服务路由规则,过滤精度高的放上边
        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**,/hello
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        # 会员服务路由规则,过滤精度高的放上边
        - id: member_route
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        # 仓储服务路由规则,过滤精度高的放上边
        - id: ware_route
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        # 第三方服务网关
        - id: third_party_route
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*),/$\{segment}

        - id: admin_route
          #lb： 表示负载均衡
          uri: lb://renren-fast
          predicates:
            #前端项目都带上/api
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/renren-fast/$\{segment}

        # nginx转发到网关路由规则
        - id: gulimall_product_route
          #lb： 表示负载均衡
          uri: lb://gulimall-product
          predicates:
            # gulimall.com的主机名都转发到product服务
            - Host=gulimall.com,item.gulimall.com

        # nginx转发到网关路由规则
        - id: gulimall_search_route
          #lb： 表示负载均衡
          uri: lb://gulimall-search
          predicates:
            # search.gulimall.com的主机名都转发到search服务
            - Host=search.gulimall.com

        # nginx转发到网关路由规则
        - id: gulimall_auth_route
          #lb： 表示负载均衡
          uri: lb://gulimall-auth-server
          predicates:
            # auth.gulimall.com的主机名都转发到auth服务
            - Host=auth.gulimall.com

        # nginx转发到网关路由规则
        - id: gulimall_cart_route
          #lb： 表示负载均衡
          uri: lb://gulimall-cart
          predicates:
            # cart.gulimall.com的主机名都转发到cart服务
            - Host=cart.gulimall.com