spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.48.110:3306/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  # classpath*表示不止扫描自己类路径下的mapper文件，也会扫描所引用的依赖中的jar包中的类路径也
  mapper-locations: classpath:/mapper/**/*.xm
  # 设置所有主键自增
  global-config:
    db-config:
      id-type: auto