spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: YourAccessKey
      secret-key: YourSecretKey
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: gulimall-syong
      sms:
        host: https://edisim.market.alicloudapi.com
        path: /comms/sms/sendmsg
        appcode: YourAppCode
        template-id: 20210604170620
    sentinel:
      transport:
        dashboard: localhost:8333

  application:
    name: gulimall-third-party

server:
  port: 30000

logging:
  level:
    com.atguigu.gulimall.product: debug

management:
  endpoints:
    web:
      exposure:
        include: *
